config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'calendar_group_reservations/index'
  resources :calendar_groups do
    resources :reservations, only: [:index], controller: 'calendar_group_reservations'
    resources :participant_reservations
    delete 'remove_user/:user_id', to: 'calendar_groups#remove_user', as: 'remove_user'
    resources :calendar_groups
  end
  resources :calendar_horses
  resources :calendar_ponies
  resources :users, only: %i[new create]
  resources :exercises
  resources :events
  resources :course_positions
  resources :users
  patch 'update_password', to: 'users#update_password'
  resources :pending_associations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
  # match '*path', to: 'errors#not_found', via: :all
  post '/support', to: 'contact#support'
  get '/calendar_groups/:calendar_group_id/participant_reservations/new_form', to: 'participant_reservations#new_form',
                                                                               as: 'new_reservation_form'
  get '/search', to: 'users#search'
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout', as: :logout
  get 'profile', to: 'users#profile', as: :profile
  get 'saved_positions', to: 'users#saved_positions', as: :saved_positions
  get 'contact/index'
  get 'about/index'
  get 'calendar_groups/index'
  get '/show_positions', to: 'course_positions#show_positions'

  post 'save_horse_exercise/:id', to: 'course_positions#save_horse_exercise', as: 'save_horse_exercise'
  post 'save_horse_course/:id', to: 'course_positions#save_horse_course', as: 'save_horse_course'
  post 'save_pony_course/:id', to: 'course_positions#save_pony_course', as: 'save_pony_course'
  post 'save_pony_exercise/:id', to: 'course_positions#save_pony_exercise', as: 'save_pony_exercise'

  get 'unsave_horse_exercise/:id', to: 'course_positions#unsave_horse_exercise', as: 'unsave_horse_exercise'
  get 'unsave_horse_course/:id', to: 'course_positions#unsave_horse_course', as: 'unsave_horse_course'
  get 'unsave_pony_course/:id', to: 'course_positions#unsave_pony_course', as: 'unsave_pony_course'
  get 'unsave_pony_exercise/:id', to: 'course_positions#unsave_pony_exercise', as: 'unsave_pony_exercise'

  get 'mark_used_horse_exercise/:id', to: 'course_positions#mark_used_horse_exercise', as: 'mark_used_horse_exercise'
  get 'mark_unused_horse_exercise/:id', to: 'course_positions#mark_unused_horse_exercise',
                                        as: 'mark_unused_horse_exercise'

  get 'mark_used_horse_course/:id', to: 'course_positions#mark_used_horse_course', as: 'mark_used_horse_course'
  get 'mark_unused_horse_course/:id', to: 'course_positions#mark_unused_horse_course', as: 'mark_unused_horse_course'

  get 'mark_used_pony_exercise/:id', to: 'course_positions#mark_used_pony_exercise', as: 'mark_used_pony_exercise'
  get 'mark_unused_pony_exercise/:id', to: 'course_positions#mark_unused_pony_exercise', as: 'mark_unused_pony_exercise'

  get 'mark_used_pony_course/:id', to: 'course_positions#mark_used_pony_course', as: 'mark_used_pony_course'
  get 'mark_unused_pony_course/:id', to: 'course_positions#mark_unused_pony_course', as: 'mark_unused_pony_course'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show"
  root 'welcome#index', as: 'welcome_page', via: :all
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/calendar_group.rb
# frozen_string_literal: true

class CalendarGroup < ApplicationRecord
  has_many :calendar_horses, dependent: :destroy
  has_many :calendar_ponies, dependent: :destroy
  has_many :participant_reservations, dependent: :destroy
  has_many :calendar_participant_join_tables, dependent: :destroy
  has_many :pending_associations, dependent: :destroy
  has_many :users, through: :calendar_participant_join_tables, validate: false

  accepts_nested_attributes_for :calendar_horses, allow_destroy: true
  accepts_nested_attributes_for :calendar_ponies, allow_destroy: true

  validates :group_name, presence: true, uniqueness: { scope: :admin_id }
end

app/controllers/calendar_groups_controller.rb
# frozen_string_literal: true

class CalendarGroupsController < ApplicationController
  before_action :set_calendar_group, only: %i[show edit update destroy]
  helper_method :admin?

  def index
    user_calendar_groups = current_user.calendar_groups
    admin_calendar_groups = CalendarGroup.where(admin_id: current_user.id)

    ordered_user_calendar_groups = user_calendar_groups.order(created_at: :desc)
    ordered_admin_calendar_groups = admin_calendar_groups.order(created_at: :desc)

    combined_calendar_groups = (ordered_user_calendar_groups + ordered_admin_calendar_groups).uniq

    @calendar_groups = Kaminari.paginate_array(combined_calendar_groups).page(params[:page]).per(5)
  end

  def show
    @calendar_group = CalendarGroup.find(params[:id])
    @reservations = @calendar_group.participant_reservations
  end

  def new
    @calendar_group = CalendarGroup.new
    @calendar_group.calendar_horses.build
    @calendar_group.calendar_ponies.build
    @pony = CalendarPony.new
    @horse = CalendarHorse.new
  end

  def edit; end

  def create
    params[:current_user_id]
    @calendar_group = CalendarGroup.new(calendar_group_params)
    @calendar_group.admin_id = current_user.id

    @calendar_group.calendar_horses = @calendar_group.calendar_horses.reject { |horse| horse.horse_name.blank? }
    @calendar_group.calendar_ponies = @calendar_group.calendar_ponies.reject { |pony| pony.pony_name.blank? }
    @calendar_group.user_ids
    @calendar_group.user_ids = []
    associate_users
    if @calendar_group.save
      @calendar_group.calendar_participant_join_tables.create(user_id: current_user.id)

      redirect_to @calendar_group, notice: 'Kalendāra grupa veiksmīgi izveidota!'
    else
      render :new
    end
  end

  def update
    if @calendar_group.calendar_horses.present?
      @calendar_group.calendar_horses = @calendar_group.calendar_horses.reject do |horse|
        horse.horse_name.blank?
      end
    end
    if @calendar_group.calendar_ponies.present?
      @calendar_group.calendar_ponies = @calendar_group.calendar_ponies.reject do |pony|
        pony.pony_name.blank?
      end
    end

    original_horse_ids = @calendar_group.calendar_horses.pluck(:id) if @calendar_group.calendar_horses.present?
    original_pony_ids = @calendar_group.calendar_ponies.pluck(:id) if @calendar_group.calendar_ponies.present?

    updated_calendar_group_params = calendar_group_params

    if updated_calendar_group_params[:calendar_horses_attributes].present?
      updated_calendar_group_params[:calendar_horses_attributes] =
        updated_calendar_group_params[:calendar_horses_attributes].reject { |_, horse| horse[:horse_name].blank? }
    end
    if updated_calendar_group_params[:calendar_ponies_attributes].present?
      updated_calendar_group_params[:calendar_ponies_attributes] =
        updated_calendar_group_params[:calendar_ponies_attributes].reject { |_, pony| pony[:pony_name].blank? }
    end

    if @calendar_group.update(updated_calendar_group_params)
      associate_users
      redirect_to @calendar_group, notice: 'Kalendāra grupa veiksmīgi atjaunināta.'
    else
      if @calendar_group.calendar_horses.present?
        @calendar_group.calendar_horses = CalendarHorse.where(id: original_horse_ids)
      end
      if @calendar_group.calendar_ponies.present?
        @calendar_group.calendar_ponies = CalendarPony.where(id: original_pony_ids)
      end
      render :edit
    end
  end

  def destroy
    @calendar_group.participant_reservations.destroy_all
    @calendar_group.calendar_horses.destroy_all
    @calendar_group.calendar_ponies.destroy_all
    @calendar_group.calendar_participant_join_tables.destroy_all
    @calendar_group.destroy

    if @calendar_group.destroyed?
      redirect_to calendar_groups_url, notice: 'Kalendāra grupa veiksmīgi dzēsta!'
    else
      redirect_to @calendar_group, alert: 'Neizdevās dzēst kalendāra grupu.'
    end
  end

  def remove_user
    calendar_group = CalendarGroup.find(params[:calendar_group_id])
    user = User.find(params[:user_id])
    calendar_group.users.delete(user)
    head :ok
  end

  private

  def admin?
    current_user.id == @calendar_group.admin_id
  end

  def set_calendar_group
    @calendar_group = CalendarGroup.find(params[:id])
  end

  def associate_users
    user_ids = params[:calendar_group][:user_ids]
    puts "User IDs: #{user_ids.inspect}"
    return unless user_ids

    user_ids = user_ids.join(',') if user_ids.is_a?(Array)
    user_ids.split(',').map(&:to_i).reject(&:zero?).each do |user_id|
      user = User.find_by(id: user_id)
      next unless user

      PendingAssociation.create(user:, calendar_group: @calendar_group) unless @calendar_group.users.include?(user)
    end
  end

  def accept_request
    pending_association = PendingAssociation.find(params[:pending_association_id])
    pending_association.update(status: 'accepted')
    @calendar_group.users << pending_association.user
    redirect_back(fallback_location: root_path)
  end

  def send_request
    user = User.find(params[:user_id])
    PendingAssociation.create(user:, calendar_group: @calendar_group)
    redirect_back(fallback_location: root_path)
  end

  def calendar_group_params
    params.require(:calendar_group).permit(
      :parallel_reservation,
      :group_name,
      calendar_horses_attributes: %i[id horse_name description _destroy],
      calendar_ponies_attributes: %i[id pony_name description _destroy],
      user_ids: []
    )
  end
end

app/helpers/calendar_groups_helper.rb
# frozen_string_literal: true

module CalendarGroupsHelper
end

app/views/calendar_groups/_horse_fields.html.erb
<!-- _horse_fields.html.erb -->
<div class="horse-fields">
  <%= f.fields_for :calendar_horses, @horse do |horse_form| %>
    <div class="mb-4">
      <%= horse_form.label :horse_name, "Horse Name", class: "block text-gray-700 text-lg font-bold mb-2" %>
      <%= horse_form.text_field :horse_name, class: "shadow appearance-none border rounded w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline text-lg" %>
    </div>
    <div class="mb-4">
      <%= horse_form.label :description, "Description", class: "block text-gray-700 text-lg font-bold mb-2" %>
      <%= horse_form.text_area :description, class: "shadow appearance-none border rounded w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline text-lg" %>
    </div>
    <!-- Button to remove horse field -->
    <button type="button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded remove-horse">Remove Horse</button>
  <% end %>
</div>

app/views/calendar_groups/_instructions.html.erb
<div class="calendar-container flex justify-between">
  <div class="info-container relative">
    <div class="info-wrapper">
      <button class="info-button text-gray-600 hover:text-gray-900 focus:outline-none focus:text-gray-900" aria-label="Info">ℹ️</button>
      <div class="info-text absolute left-5 mb-9 bg-white border border-gray-200 rounded-lg shadow-md p-4 overflow-hidden hidden">
        <div class="info-text-content overflow-auto">
          <strong class="block mb-2">Kalendāra lietošanas pamācība</strong>
          <ol class="list-decimal pl-5">
            <li>
              Jauna rezervācija:
              <ul class="list-disc pl-5">
                <li>Noklikšķiniet uz datuma.</li>
                <li>Aizpildiet rezervācijas datus.</li>
                <li>Nospiediet apstiprināt pogu.</li>
              </ul>
            </li>
            <li class="mt-3">
              Rediģēt rezervāciju:
              <ol class="pl-5">
                <li>
                  <span>2.1 Parasts lietotājs:</span>
                  <ul class="list-disc pl-9">
                    <li>Noklikšķiniet uz rezervācijas, kas ir zaļā krāsa.</li>
                    <li>Veiciet izmaiņas.</li>
                    <li>Nospiediet apstiprināt pogu.</li>
                  </ul>
                </li>
                <li>
                  <span>2.2 Administrators:</span>
                  <ul class="list-disc pl-9">
                    <li>Noklikšķiniet uz rezervācijas (gan sarkanās, gan zaļās).</li>
                    <li>Veiciet izmaiņas.</li>
                    <li>Nospiediet apstiprināt pogu.</li>
                  </ul>
                </li>
              </ol>
            </li>
            <li class="mt-3">
              Paralēlā rezervācija
              <ol class="pl-5">
                <li>
                  <span>3.1 Aktīva:</span>
                  <ul class="list-disc pl-9">
                    <li>Var veikt rezervāciju pārklājoties laikiem ar izvēlēto zirgu vai poniju, tikai tad ja izvēlētais zirgs vai ponijs jau nav laika periodā izvēlēts.</li>
                  </ul>
                </li>
                <li>
                  <span>2.2 Nav aktīva:</span>
                  <ul class="list-disc pl-9">
                    <li>Rezervāciju nevar veikt nekādā gadījumā, ja izvēlētais laiks pārklājas.</li>
                  </ul>
                </li>
              </ol>
            </li>
            <li class="mt-3">
              Lai rediģētu grupu, jānospiež poga "Rediģēt" (spēj tikai kalendāra administrators).
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>

app/views/calendar_groups/_pony_fields.html.erb
<!-- _pony_fields.html.erb -->
<div class="pony-fields">
  <%= f.fields_for :calendar_ponies, @pony do |pony_form| %>
    <div class="mb-4">
      <%= pony_form.label :pony_name, "Pony Name", class: "block text-gray-700 text-lg font-bold mb-2" %>
      <%= pony_form.text_field :pony_name, class: "shadow appearance-none border rounded w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline text-lg" %>
    </div>
    <div class="mb-4">
      <%= pony_form.label :description, "Description", class: "block text-gray-700 text-lg font-bold mb-2" %>
      <%= pony_form.text_area :description, class: "shadow appearance-none border rounded w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline text-lg" %>
    </div>
    <!-- Button to remove pony field -->
    <button type="button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded remove-pony">Remove Pony</button>
  <% end %>
</div>

app/views/calendar_groups/edit.html.erb
<div class="p-4 flex items-center justify-between">
  <%= link_to calendar_group_path(@calendar_group), class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white mr-4" do %>
    <%= image_tag("arrow.svg", alt: "Arrow button", class: "w-6 h-6") %>
  <% end %>
  <div class="text-center">
    <h1 class="text-3xl font-bold">Rediģēt grupu "<%= @calendar_group.group_name%>"</h1>
  </div>
  <div></div>
</div>
<%= render 'form', calendar_group: @calendar_group %>

app/views/calendar_groups/index.html.erb
<div class="flex flex-col items-center justify-between mt-4">
  <h1 class="text-black text-center text-xl font-bold">Jūsu treniņu kalendāri</h1>
</div>
<div class="flex justify-end">
  <%= link_to 'Izveidot kalendāra grupu', new_calendar_group_path, class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white" %>
</div>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @calendar_groups %>
</div>
<div class="flex justify-center mt-3 ml-5">
  <% if @calendar_groups.present? %>
    <ul class="mb-1 w-full">
      <% @calendar_groups.each do |calendar_group| %>
        <li class="border-b border-gray-600 mb-2 pb-3 text-center shadow-md bg-gray-50  p-4">
          <%= link_to calendar_group.group_name, calendar_group_path(calendar_group, current_user_id: current_user.id), class: "text-lg font-bold cursor-pointer text-center" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Jums nav nevienas kalendāra grupas</p>
  <% end %>
</div>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @calendar_groups %>
</div>

app/views/calendar_groups/new.html.erb
<div class="p-4">
  <div class="p-4 flex items-center justify-between">
    <%= link_to calendar_groups_path, class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white mr-4" do %>
      <%= image_tag("arrow.svg", alt: "Arrow button", class: "w-6 h-6") %>
    <% end %>
    <div class="text-center">
      <h1 class="text-3xl font-bold">Jauna kalendāra grupa</h1>
    </div>
    <div></div>
  </div>
  <%= render 'form', calendar_group: @calendar_group %>
</div>