config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'calendar_group_reservations/index'
  resources :calendar_groups do
    resources :reservations, only: [:index], controller: 'calendar_group_reservations'
    resources :participant_reservations
    delete 'remove_user/:user_id', to: 'calendar_groups#remove_user', as: 'remove_user'
    resources :calendar_groups
  end
  resources :calendar_horses
  resources :calendar_ponies
  resources :users, only: %i[new create]
  resources :exercises
  resources :events
  resources :course_positions
  resources :users
  patch 'update_password', to: 'users#update_password'
  resources :pending_associations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
  # match '*path', to: 'errors#not_found', via: :all
  post '/support', to: 'contact#support'
  get '/calendar_groups/:calendar_group_id/participant_reservations/new_form', to: 'participant_reservations#new_form',
                                                                               as: 'new_reservation_form'
  get '/search', to: 'users#search'
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout', as: :logout
  get 'profile', to: 'users#profile', as: :profile
  get 'saved_positions', to: 'users#saved_positions', as: :saved_positions
  get 'contact/index'
  get 'about/index'
  get 'calendar_groups/index'
  get '/show_positions', to: 'course_positions#show_positions'

  post 'save_horse_exercise/:id', to: 'course_positions#save_horse_exercise', as: 'save_horse_exercise'
  post 'save_horse_course/:id', to: 'course_positions#save_horse_course', as: 'save_horse_course'
  post 'save_pony_course/:id', to: 'course_positions#save_pony_course', as: 'save_pony_course'
  post 'save_pony_exercise/:id', to: 'course_positions#save_pony_exercise', as: 'save_pony_exercise'

  get 'unsave_horse_exercise/:id', to: 'course_positions#unsave_horse_exercise', as: 'unsave_horse_exercise'
  get 'unsave_horse_course/:id', to: 'course_positions#unsave_horse_course', as: 'unsave_horse_course'
  get 'unsave_pony_course/:id', to: 'course_positions#unsave_pony_course', as: 'unsave_pony_course'
  get 'unsave_pony_exercise/:id', to: 'course_positions#unsave_pony_exercise', as: 'unsave_pony_exercise'

  get 'mark_used_horse_exercise/:id', to: 'course_positions#mark_used_horse_exercise', as: 'mark_used_horse_exercise'
  get 'mark_unused_horse_exercise/:id', to: 'course_positions#mark_unused_horse_exercise',
                                        as: 'mark_unused_horse_exercise'

  get 'mark_used_horse_course/:id', to: 'course_positions#mark_used_horse_course', as: 'mark_used_horse_course'
  get 'mark_unused_horse_course/:id', to: 'course_positions#mark_unused_horse_course', as: 'mark_unused_horse_course'

  get 'mark_used_pony_exercise/:id', to: 'course_positions#mark_used_pony_exercise', as: 'mark_used_pony_exercise'
  get 'mark_unused_pony_exercise/:id', to: 'course_positions#mark_unused_pony_exercise', as: 'mark_unused_pony_exercise'

  get 'mark_used_pony_course/:id', to: 'course_positions#mark_used_pony_course', as: 'mark_used_pony_course'
  get 'mark_unused_pony_course/:id', to: 'course_positions#mark_unused_pony_course', as: 'mark_unused_pony_course'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show"
  root 'welcome#index', as: 'welcome_page', via: :all
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
# frozen_string_literal: true

# app/models/user.rb
class User < ApplicationRecord
  # ----calendar reservations
  has_many :calendar_participant_join_tables, dependent: :destroy
  has_many :calendar_groups, through: :calendar_participant_join_tables
  has_many :exercises, dependent: :destroy
  has_many :pending_associations, dependent: :destroy
  #------related to all courses and exercises----------------
  has_many :pony_courses_users, dependent: :destroy
  has_many :pony_courses, through: :pony_courses_users, dependent: :destroy
  #--------------------------
  has_many :pony_exercises_users, dependent: :destroy
  has_many :pony_exercises, through: :pony_exercises_users, dependent: :destroy
  #--------------------------
  has_many :horse_courses_users, dependent: :destroy
  has_many :horse_courses, through: :horse_courses_users, dependent: :destroy
  #--------------------------
  has_many :horse_exercises_users, dependent: :destroy
  has_many :horse_exercises, through: :horse_exercises_users, dependent: :destroy
  #--------validations-----------------
  has_secure_password
  validates :name, presence: true
  validates :surname, presence: true

  validates :username, uniqueness: true, if: :username_changed?
  validates :email, presence: true, uniqueness: true, if: :email_changed?

  validates :password, presence: true, length: { minimum: 8 }, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?
  mount_uploader :avatar, AvatarUploader
  validate :avatar_content_type

  private

  def password_required?
    new_record? || password.present? || password_confirmation.present?
  end

  def avatar_content_type
    return unless avatar.present?

    return if avatar.content_type.in?(%w[image/jpeg image/png])

    errors.add('Failām jābūt png vai jpeg formātā!')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# app/controllers/users_controller.rb
require 'base64'
class UsersController < ApplicationController
  before_action :set_user, only: [:update_password]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def login
    @user = User.new
  end

  def profile
    @user = current_user
  end

  def create

    @user = User.new(user_params)
    if params[:cropped_image_data].present?
      # Decode the Base64 image
      image_data = Base64.decode64(params[:cropped_image_data].split(',')[1])
      # Create a file from the decoded data
      temp_img_file = Tempfile.new(['cropped_avatar', '.png'])
      temp_img_file.binmode
      temp_img_file.write(image_data)
      temp_img_file.rewind

      # Upload the image using CarrierWave
      @user.avatar = temp_img_file
      temp_img_file.close
      temp_img_file.unlink # delete the temp file
    end
    respond_to do |format|
      if @user.save
        create_calendar_group(@user)
        format.html do
          redirect_to login_path, notice: t('user_created')
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @user.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to profile_path, notice: 'Jūsu profils ir veiksmīgi atjaunināts'
    else
      render :profile
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to welcome_page_url, notice: t('logged_out')
  end

  def authenticate
    @user = User.find_by(username: params[:username])
    if !params[:username].blank? || !params[:password].blank?
      if @user&.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to welcome_page_url, notice: t('logged_in', name: @user.name)
      else
        @user ||= User.new(username: params[:username])
        @user.errors.add(:base, 'Nederīgs lietotājvārds vai parole!')
        render :login
      end
    else
      @user ||= User.new(username: params[:username])
      @user.errors.add(:base, 'Lauki nevar būt tukši!')
      render :login
    end
  end

  def destroy
    @user = User.find(params[:id])
    # Find calendar groups where the user is an admin
    admin_groups = CalendarGroup.where(admin_id: @user.id)

    # Iterate over each admin group
    admin_groups.each do |group|
      # Find participant reservations associated with this group
      reservations = ParticipantReservation.where(calendar_group_id: group.id)

      # If the admin group has only one participant reservation,
      # delete the calendar group
      if reservations.count <= 1
        group.destroy
      else
        # If there are other participants, transfer admin role
        # to the first participant
        first_participant = reservations.first
        group.update(admin_id: first_participant.created_by_id)
      end
    end
    if @user.destroy
      redirect_to welcome_page_url, notice: 'Jūsu profils ir veiksmīgi dzēsts!'
    else
      redirect_to welcome_page_url, error: 'Radās kļūda dzēšot profilu!'
    end
  end

  def search
    term = params[:term]
    if !term.blank?
      @users = User.where('username LIKE ?', "%#{term}%").limit(6)
      if @users.blank?
        render json: { error: 'Nav atrasts neviens lietotājs' }
      else
        render json: { users: @users }
      end
    else
      render json: { error: 'Ievadiet lietotājvārdu' }
    end
  end

  def update_password
    if @user.authenticate(params[:user][:previous_password])
      if password_present?
        if @user.update(user_params)
          redirect_to profile_path, notice: 'Parole atjaunināta'
        else
          render :profile
        end
      else
        @user.errors.add(:password, 'Jaunā parole un atkārotā nevar būt tukša')
        render :profile
      end
    else
      @user.errors.add(:password, 'Esošā parole nav pareiza')
      render :profile
    end
  end

  private

  def password_present?
    params[:user][:password].present? && params[:user][:password_confirmation].present?
  end

  def set_user
    @user = current_user
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation, :previous_password)
  end

  def create_calendar_group(user)
    @calendar_group = CalendarGroup.new(admin_id: user.id)
    @calendar_group.group_name = "#{user.username} kalendāra grupa"
    @calendar_group.users << user
    @calendar_group.save
  end

  def error_message
    if @user.errors.any?
      @user.errors.full_messages.join(', ')
    else
      'An unknown error occurred.'
    end
  end

  def user_params
    params.require(:user).permit(:name, :surname, :username, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_horse_course_profle.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
  <h3 class="font-bold cursor-pointer text-center" @click="open = !open">
    <%= exercise.title %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
      <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
    </svg>
  </h3>
  <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
    <div class=" mb-4 pb-4 mr-5 flex">
      <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
        <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
          <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
          <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
            <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
            <!-- Show more/less button -->
            <% if exercise.description.length > 50 %>
              <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Canvas Image -->
      <div class=" w-full" id="canvas_container_<%= exercise.id %>">
        <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
          <div class="image-wrapper items-center justify-center">
            <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
            <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
          </div>
        </div>
      </div>
      <div class="popup-container" style="display: none;">
        <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
          <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
            <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
          </button>
          <img class="full-image" src="" alt="Full Image">
          <div class="popup-options flex">
            <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
              <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
            </button>
            <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
              <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-2 items-center" style="display: flex; justify-content: center; width: 100%;">
      <div >
        <p class="font-bold mr-2 inline-block">Atzīmēt novietojumu kā:</p>
        <% if horse_courses_user.used %>
          <%= link_to "Neizmantots", mark_unused_horse_course_path(horse_courses_user.horse_course), method: :get, class: "bg-orange-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% else %>
          <%= link_to "Izmantots", mark_used_horse_course_path(horse_courses_user.horse_course), method: :get, class: "bg-green-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% end %>
      </div>
    </div>
    <div class="mt-2 items-center w-full" style="display: flex; justify-content: center;">
      <div>
        <% if horse_courses_user.saved %>
          <%= link_to "Dzēst no profila", unsave_horse_course_path(horse_courses_user.horse_course), method: :get, remote: :false, class: "bg-red-500 text-white rounded-full py-2 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_horse_exercise_profle.html.erb
 <%= javascript_include_tag 'show_exercises' %>
<div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
  <h3 class=" font-bold cursor-pointer text-center" @click="open = !open">
    <%= exercise.title %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
      <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
    </svg>
  </h3>
  <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
    <div class="mb-4 pb-4 mr-5 flex">
      <div class="mb-4 mt-2  w-full" id="description-container-<%= exercise.id %>">
        <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
          <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
          <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
            <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
            <!-- Show more/less button -->
            <% if exercise.description.length > 50 %>
              <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Canvas Image -->
      <div class=" w-full" id="canvas_container_<%= exercise.id %>">
        <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
          <div class="image-wrapper items-center justify-center">
            <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
            <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
          </div>
        </div>
      </div>
      <div class="popup-container" style="display: none;">
        <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
          <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
            <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
          </button>
          <img class="full-image" src="" alt="Full Image">
          <div class="popup-options flex">
            <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
              <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
            </button>
            <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
              <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-2 items-center" style="display: flex; justify-content: center; width: 100%;">
      <div >
        <p class="font-bold mr-2 inline-block">Atzīmēt novietojumu kā:</p>
        <% if horse_exercises_user.used %>
          <%= link_to "Neizmantots", mark_unused_horse_exercise_path(horse_exercises_user.horse_exercise), method: :get, class: "bg-orange-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% else %>
          <%= link_to "Izmantots", mark_used_horse_exercise_path(horse_exercises_user.horse_exercise), method: :get, class: "bg-green-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% end %>
      </div>
    </div>
    <div class="mt-2 items-center w-full" style="display: flex; justify-content: center;">
      <div>
        <% if horse_exercises_user.saved %>
          <%= link_to "Dzēst no profila",  unsave_horse_exercise_path(horse_exercises_user.horse_exercise), method: :get, remote: :false, class: "bg-red-500 text-white rounded-full py-2 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_pony_course_profle.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
  <h3 class=" font-bold cursor-pointer text-center" @click="open = !open">
    <%= exercise.title %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
      <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
    </svg>
  </h3>
  <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
    <div class=" mb-4 pb-4 mr-5 flex">
      <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
        <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
          <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
          <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
            <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
            <!-- Show more/less button -->
            <% if exercise.description.length > 50 %>
              <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Canvas Image -->
      <div class=" w-full" id="canvas_container_<%= exercise.id %>">
        <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
          <div class="image-wrapper items-center justify-center">
            <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
            <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
          </div>
        </div>
      </div>
      <div class="popup-container" style="display: none;">
        <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
          <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
            <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
          </button>
          <img class="full-image" src="" alt="Full Image">
          <div class="popup-options flex">
            <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
              <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
            </button>
            <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
              <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-2 items-center" style="display: flex; justify-content: center; width: 100%;">
      <div >
        <p class="font-bold mr-2 inline-block">Atzīmēt novietojumu kā:</p>
        <% if pony_course_user.used %>
          <%= link_to "Neizmantots", mark_unused_pony_course_path(pony_course_user.pony_course), method: :get, class: "bg-orange-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% else %>
          <%= link_to "Izmantots", mark_used_pony_course_path(pony_course_user.pony_course), method: :get, class: "bg-green-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% end %>
      </div>
    </div>
    <div class="mt-2 items-center w-full" style="display: flex; justify-content: center;">
      <div>
        <% if pony_course_user.saved %>
          <%= link_to "Dzēst no profila", unsave_pony_course_path(pony_course_user.pony_course), method: :get, remote: :false, class: "bg-red-500 text-white rounded-full py-2 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_pony_exercise_profle.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
  <h3 class="font-bold cursor-pointer text-center" @click="open = !open">
    <%= exercise.title %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
      <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
    </svg>
  </h3>
  <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
    <div class=" mb-4 pb-4 mr-5 flex">
      <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
        <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
          <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
          <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
            <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
            <!-- Show more/less button -->
            <% if exercise.description.length > 50 %>
              <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Canvas Image -->
      <div class=" w-full" id="canvas_container_<%= exercise.id %>">
        <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
          <div class="image-wrapper items-center justify-center">
            <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
            <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
          </div>
        </div>
      </div>
      <div class="popup-container" style="display: none;">
        <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
          <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
            <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
          </button>
          <img class="full-image" src="" alt="Full Image">
          <div class="popup-options flex">
            <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
              <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
            </button>
            <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
              <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-2 items-center" style="display: flex; justify-content: center; width: 100%;">
      <div >
        <p class="font-bold mr-2 inline-block">Atzīmēt novietojumu kā:</p>
        <% if pony_exercises_user.used %>
          <%= link_to "Neizmantots", mark_unused_pony_exercise_path(pony_exercises_user.pony_exercise), method: :get, class: "bg-orange-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% else %>
          <%= link_to "Izmantots", mark_used_pony_exercise_path(pony_exercises_user.pony_exercise), method: :get, class: "bg-green-500 text-white rounded-full py-2 px-4 mr-2 inline-block" %>
        <% end %>
      </div>
    </div>
    <div class="mt-2 items-center w-full" style="display: flex; justify-content: center;">
      <div>
        <% if pony_exercises_user.saved%>
          <%= link_to "Dzēst no profila",  unsave_pony_exercise_path(pony_exercises_user.pony_exercise), method: :get, class: "bg-red-500 text-white rounded-full py-2 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>