config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'calendar_group_reservations/index'
  resources :calendar_groups do
    resources :reservations, only: [:index], controller: 'calendar_group_reservations'
    resources :participant_reservations
    delete 'remove_user/:user_id', to: 'calendar_groups#remove_user', as: 'remove_user'
    resources :calendar_groups
  end
  resources :calendar_horses
  resources :calendar_ponies
  resources :users, only: %i[new create]
  resources :exercises
  resources :events
  resources :course_positions
  resources :users
  patch 'update_password', to: 'users#update_password'
  resources :pending_associations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
  # match '*path', to: 'errors#not_found', via: :all
  post '/support', to: 'contact#support'
  get '/calendar_groups/:calendar_group_id/participant_reservations/new_form', to: 'participant_reservations#new_form',
                                                                               as: 'new_reservation_form'
  get '/search', to: 'users#search'
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout', as: :logout
  get 'profile', to: 'users#profile', as: :profile
  get 'saved_positions', to: 'users#saved_positions', as: :saved_positions
  get 'contact/index'
  get 'about/index'
  get 'calendar_groups/index'
  get '/show_positions', to: 'course_positions#show_positions'

  post 'save_horse_exercise/:id', to: 'course_positions#save_horse_exercise', as: 'save_horse_exercise'
  post 'save_horse_course/:id', to: 'course_positions#save_horse_course', as: 'save_horse_course'
  post 'save_pony_course/:id', to: 'course_positions#save_pony_course', as: 'save_pony_course'
  post 'save_pony_exercise/:id', to: 'course_positions#save_pony_exercise', as: 'save_pony_exercise'

  get 'unsave_horse_exercise/:id', to: 'course_positions#unsave_horse_exercise', as: 'unsave_horse_exercise'
  get 'unsave_horse_course/:id', to: 'course_positions#unsave_horse_course', as: 'unsave_horse_course'
  get 'unsave_pony_course/:id', to: 'course_positions#unsave_pony_course', as: 'unsave_pony_course'
  get 'unsave_pony_exercise/:id', to: 'course_positions#unsave_pony_exercise', as: 'unsave_pony_exercise'

  get 'mark_used_horse_exercise/:id', to: 'course_positions#mark_used_horse_exercise', as: 'mark_used_horse_exercise'
  get 'mark_unused_horse_exercise/:id', to: 'course_positions#mark_unused_horse_exercise',
                                        as: 'mark_unused_horse_exercise'

  get 'mark_used_horse_course/:id', to: 'course_positions#mark_used_horse_course', as: 'mark_used_horse_course'
  get 'mark_unused_horse_course/:id', to: 'course_positions#mark_unused_horse_course', as: 'mark_unused_horse_course'

  get 'mark_used_pony_exercise/:id', to: 'course_positions#mark_used_pony_exercise', as: 'mark_used_pony_exercise'
  get 'mark_unused_pony_exercise/:id', to: 'course_positions#mark_unused_pony_exercise', as: 'mark_unused_pony_exercise'

  get 'mark_used_pony_course/:id', to: 'course_positions#mark_used_pony_course', as: 'mark_used_pony_course'
  get 'mark_unused_pony_course/:id', to: 'course_positions#mark_unused_pony_course', as: 'mark_unused_pony_course'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show"
  root 'welcome#index', as: 'welcome_page', via: :all
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/course_positions_controller.rb
# frozen_string_literal: true

class CoursePositionsController < ApplicationController
  def show_positions
    choice = params[:choice]

    case choice
    when 'Poniju maršruti'
      @pony_courses = PonyCourse.order(created_at: :desc).page(params[:page]).per(8)
    when 'Poniju vingrinājumi'
      @pony_exercises = PonyExercise.order(created_at: :desc).page(params[:page]).per(8)
    when 'Zirgu maršruti'
      @horse_courses = HorseCourse.order(created_at: :desc).page(params[:page]).per(8)
    when 'Zirgu vingrinājumi'
      @horse_exercises = HorseExercise.order(created_at: :desc).page(params[:page]).per(8)
    else
      redirect_to course_positions_path, notice: 'Notika kļūda'
    end
  end

  def save_horse_exercise
    @exercise = HorseExercise.find(params[:id])
    if current_user.horse_exercises_users.exists?(horse_exercise_id: @exercise.id, saved: true)
      flash[:alert] = 'Vingrinājums jau ir saglabāts.'
    else
      current_user.horse_exercises << @exercise
      @exercise.horse_exercises_users.find_or_create_by(user_id: current_user.id).update(saved: true)
      flash[:notice] = 'Vingrinājums veiksmīgi saglabāts'
    end
    redirect_back(fallback_location: welcome_page_path)
  end

  def save_horse_course
    @exercise = HorseCourse.find(params[:id])
    if current_user.horse_courses_users.exists?(horse_course_id: @exercise.id, saved: true)
      flash[:alert] = 'Maršruts jau ir saglabāts.'
    else
      current_user.horse_courses << @exercise
      @exercise.horse_courses_users.find_or_create_by(user_id: current_user.id).update(saved: true)
      flash[:notice] = 'Maršruts veiksmīgi saglabāts'
    end
    redirect_back(fallback_location: welcome_page_path)
  end

  def save_pony_course
    @exercise = PonyCourse.find(params[:id])
    if current_user.pony_courses_users.exists?(pony_course_id: @exercise.id, saved: true)
      flash[:alert] = 'Maršruts jau ir saglabāts.'
    else
      current_user.pony_courses << @exercise
      @exercise.pony_courses_users.find_or_create_by(user_id: current_user.id).update(saved: true)
      flash[:notice] = 'Maršruts veiksmīgi saglabāts'
    end
    redirect_back(fallback_location: welcome_page_path)
  end

  def save_pony_exercise
    @exercise = PonyExercise.find(params[:id])
    if current_user.pony_exercises_users.exists?(pony_exercise_id: @exercise.id, saved: true)
      flash[:alert] = 'Vingrinājums jau ir saglabāts.'
    else
      current_user.pony_exercises << @exercise
      @exercise.pony_exercises_users.find_or_create_by(user_id: current_user.id).update(saved: true)
      flash[:notice] = 'Vingrinājums veiksmīgi saglabāts'
    end
    redirect_back(fallback_location: welcome_page_path)
  end

  def unsave_horse_exercise
    @exercise = HorseExercise.find(params[:id])
    horse_exercise_user = current_user.horse_exercises_users.find_by(horse_exercise_id: @exercise.id)
    if horse_exercise_user&.used
      horse_exercise_user.update(saved: false)
      redirect_to profile_path, notice: 'Vingrinājums ir veiksmīgi noņemts'
    else
      current_user.horse_exercises.delete(@exercise)
    end
  end

  def unsave_horse_course
    @exercise = HorseCourse.find(params[:id])
    horse_course_user = current_user.horse_courses_users.find_by(horse_course_id: @exercise.id)
    if horse_course_user&.used
      horse_course_user.update(saved: false)
      redirect_to profile_path, notice: 'Maršruts ir veiksmīgi noņemts'
    else
      current_user.horse_courses.delete(@exercise)
    end
  end

  def unsave_pony_course
    @exercise = PonyCourse.find(params[:id])
    pony_course_user = current_user.pony_courses_users.find_by(pony_course_id: @exercise.id)
    if pony_course_user&.used
      pony_course_user.update(saved: false)
      redirect_to profile_path, notice: 'Maršruts ir veiksmīgi noņemts'
    else
      current_user.pony_courses.delete(@exercise)
    end
  end

  def unsave_pony_exercise
    @exercise = PonyExercise.find(params[:id])
    pony_exercise_user = current_user.pony_exercises_users.find_by(pony_exercise_id: @exercise.id)
    if pony_exercise_user&.used
      pony_exercise_user.update(saved: false)
      redirect_to profile_path, notice: 'Vingrinājums ir veiksmīgi noņemts'
    else
      current_user.pony_exercises.delete(@exercise)
    end
  end

  def mark_used_horse_exercise
    @exercise = HorseExercise.find(params[:id])
    horse_exercise_user = current_user.horse_exercises_users.find_by(horse_exercise_id: @exercise.id)
    horse_exercise_user.update(used: true)
    redirect_to profile_path, notice: 'Vingrinājums ir atzīmēts kā izmantots'
  end

  # Mark Horse Exercise as unused
  def mark_unused_horse_exercise
    @exercise = HorseExercise.find(params[:id])
    horse_exercise_user = current_user.horse_exercises_users.find_by(horse_exercise_id: @exercise.id)
    horse_exercise_user.update(used: false)
    redirect_to profile_path, notice: 'Vingrinājums ir atzīmēts kā neizmantots'
  end

  # Mark Horse Course as used
  def mark_used_horse_course
    @course = HorseCourse.find(params[:id])
    horse_course_user = current_user.horse_courses_users.find_by(horse_course_id: @course.id)
    horse_course_user.update(used: true)
    redirect_to profile_path, notice: 'Maršruts ir atzīmēts kā izmantots'
  end

  # Mark Horse Course as unused
  def mark_unused_horse_course
    @course = HorseCourse.find(params[:id])
    horse_course_user = current_user.horse_courses_users.find_by(horse_course_id: @course.id)
    horse_course_user.update(used: false)
    redirect_to profile_path, notice: 'Maršruts ir atzīmēts kā neizmantots'
  end

  # Mark Pony Exercise as used
  def mark_used_pony_exercise
    @exercise = PonyExercise.find(params[:id])
    pony_exercise_user = current_user.pony_exercises_users.find_by(pony_exercise_id: @exercise.id)
    pony_exercise_user.update(used: true)
    redirect_to profile_path, notice: 'Vingrinājums ir atzīmēts kā izmantots'
  end

  # Mark Pony Exercise as unused
  def mark_unused_pony_exercise
    @exercise = PonyExercise.find(params[:id])
    pony_exercise_user = current_user.pony_exercises_users.find_by(pony_exercise_id: @exercise.id)
    pony_exercise_user.update(used: false)
    redirect_to profile_path, notice: 'Vingrinājums ir atzīmēts kā neizmantots'
  end

  # Mark Pony Course as used
  def mark_used_pony_course
    @course = PonyCourse.find(params[:id])
    pony_course_user = current_user.pony_courses_users.find_by(pony_course_id: @course.id)
    pony_course_user.update(used: true)
    redirect_to profile_path, notice: 'Maršruts ir atzīmēts kā izmantots'
  end

  # Mark Pony Course as unused
  def mark_unused_pony_course
    @course = PonyCourse.find(params[:id])
    pony_course_user = current_user.pony_courses_users.find_by(pony_course_id: @course.id)
    pony_course_user.update(used: false)
    redirect_to profile_path, notice: 'Maršruts ir atzīmēts kā neizmantots'
  end
end

app/views/course_positions/_horse_courses.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @horse_courses %>
</div>
<% if horse_courses.any? %>
  <% horse_courses.each do |exercise| %>
    <div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
      <h3 class="text-lg font-bold cursor-pointer text-center" @click="open = !open">
        <%= exercise.title %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
          <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
        </svg>
      </h3>
      <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
        <div class=" mb-4 pb-4 mr-5 flex">
          <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
            <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
              <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
              <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
                <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
                <!-- Show more/less button -->
                <% if exercise.description.length > 50 %>
                  <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Canvas Image -->
          <div class=" w-full" id="canvas_container_<%= exercise.id %>">
            <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
              <div class="image-wrapper items-center justify-center">
                <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
                <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
              </div>
            </div>
          </div>
          <div class="popup-container" style="display: none;">
            <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
              <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
                <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
              </button>
              <img class="full-image" src="" alt="Full Image">
              <div class="popup-options flex">
                <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
                  <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
                </button>
                <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
                  <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-2" style="display: flex; justify-content: center;">
          <%= button_to save_horse_course_path(exercise), class: "bg-green-500 text-white rounded-full py-2 px-4 inline-block" do %>
            Saglabāt
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-black text-center">Nav izveidotu novietojumu</p>
<% end %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @horse_courses %>
</div>

app/views/course_positions/_horse_exercises.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @horse_exercises %>
</div>
<% if horse_exercises.any? %>
  <% horse_exercises.each do |exercise| %>
    <div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
      <h3 class="text-lg font-bold cursor-pointer text-center" @click="open = !open">
        <%= exercise.title %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
          <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
        </svg>
      </h3>
      <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
        <div class="mb-4 pb-4 mr-5 flex">
          <div class="mb-4 mt-2  w-full" id="description-container-<%= exercise.id %>">
            <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
              <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
              <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
                <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
                <!-- Show more/less button -->
                <% if exercise.description.length > 50 %>
                  <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Canvas Image -->
          <div class=" w-full" id="canvas_container_<%= exercise.id %>">
            <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
              <div class="image-wrapper items-center justify-center">
                <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
                <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
              </div>
            </div>
          </div>
          <div class="popup-container" style="display: none;">
            <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
              <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
                <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
              </button>
              <img class="full-image" src="" alt="Full Image">
              <div class="popup-options flex">
                <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
                  <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
                </button>
                <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
                  <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-2" style="display: flex; justify-content: center;">
          <%= button_to save_horse_exercise_path(exercise), class: "bg-green-500 text-white rounded-full py-2 px-4 inline-block" do %>
            Saglabāt
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-black text-center">Nav izveidotu novietojumu</p>
<% end %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @horse_exercises %>
</div>

app/views/course_positions/_pony_courses.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @pony_courses %>
</div>
<% if pony_courses.any? %>
  <% pony_courses.each do |exercise| %>
    <div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
      <h3 class="text-lg font-bold cursor-pointer text-center" @click="open = !open">
        <%= exercise.title %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
          <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
        </svg>
      </h3>
      <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
        <div class=" mb-4 pb-4 mr-5 flex">
          <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
            <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
              <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
              <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
                <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
                <!-- Show more/less button -->
                <% if exercise.description.length > 50 %>
                  <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Canvas Image -->
          <div class=" w-full" id="canvas_container_<%= exercise.id %>">
            <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
              <div class="image-wrapper items-center justify-center">
                <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
                <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
              </div>
            </div>
          </div>
          <div class="popup-container" style="display: none;">
            <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
              <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
                <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
              </button>
              <img class="full-image" src="" alt="Full Image">
              <div class="popup-options flex">
                <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
                  <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
                </button>
                <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
                  <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-2" style="display: flex; justify-content: center;">
          <%= button_to save_pony_course_path(exercise), class: "bg-green-500 text-white rounded-full py-2 px-4 inline-block" do %>
            Saglabāt
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-black text-center">Nav izveidotu novietojumu</p>
<% end %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @pony_courses %>
</div>

app/views/course_positions/_pony_exercises.html.erb
<%= javascript_include_tag 'show_exercises' %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @pony_exercises %>
</div>
<% if pony_exercises.any? %>
  <% pony_exercises.each do |exercise| %>
    <div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
      <h3 class="text-lg font-bold cursor-pointer text-center" @click="open = !open">
        <%= exercise.title %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
          <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
        </svg>
      </h3>
      <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
        <div class=" mb-4 pb-4 mr-5 flex">
          <div class="mb-4 mt-2 w-full" id="description-container-<%= exercise.id %>">
            <div class="flex flex-col items-center rounded-lg bg-gray-100 p-4 shadow-md">
              <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
              <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
                <p id="exercise_description_text_<%= exercise.id %>"><%= exercise.description %></p>
                <!-- Show more/less button -->
                <% if exercise.description.length > 50 %>
                  <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Canvas Image -->
          <div class=" w-full" id="canvas_container_<%= exercise.id %>">
            <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
              <div class="image-wrapper items-center justify-center">
                <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
                <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
              </div>
            </div>
          </div>
          <div class="popup-container" style="display: none;">
            <div class="popup-content relative" data-exercise-name="<%= exercise.title %>">
              <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
                <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
              </button>
              <img class="full-image" src="" alt="Full Image">
              <div class="popup-options flex">
                <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
                  <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
                </button>
                <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
                  <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-2" style="display: flex; justify-content: center;">
          <%= button_to save_pony_exercise_path(exercise), class: "bg-green-500 text-white rounded-full py-2 px-4 inline-block" do %>
            Saglabāt
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-black text-center">Nav izveidotu novietojumu</p>
<% end %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @pony_exercises %>
</div>