config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'calendar_group_reservations/index'
  resources :calendar_groups do
    resources :reservations, only: [:index], controller: 'calendar_group_reservations'
    resources :participant_reservations
    delete 'remove_user/:user_id', to: 'calendar_groups#remove_user', as: 'remove_user'
    resources :calendar_groups
  end
  resources :calendar_horses
  resources :calendar_ponies
  resources :users, only: %i[new create]
  resources :exercises
  resources :events
  resources :course_positions
  resources :users
  patch 'update_password', to: 'users#update_password'
  resources :pending_associations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end
  # match '*path', to: 'errors#not_found', via: :all
  post '/support', to: 'contact#support'
  get '/calendar_groups/:calendar_group_id/participant_reservations/new_form', to: 'participant_reservations#new_form',
                                                                               as: 'new_reservation_form'
  get '/search', to: 'users#search'
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout', as: :logout
  get 'profile', to: 'users#profile', as: :profile
  get 'saved_positions', to: 'users#saved_positions', as: :saved_positions
  get 'contact/index'
  get 'about/index'
  get 'calendar_groups/index'
  get '/show_positions', to: 'course_positions#show_positions'

  post 'save_horse_exercise/:id', to: 'course_positions#save_horse_exercise', as: 'save_horse_exercise'
  post 'save_horse_course/:id', to: 'course_positions#save_horse_course', as: 'save_horse_course'
  post 'save_pony_course/:id', to: 'course_positions#save_pony_course', as: 'save_pony_course'
  post 'save_pony_exercise/:id', to: 'course_positions#save_pony_exercise', as: 'save_pony_exercise'

  get 'unsave_horse_exercise/:id', to: 'course_positions#unsave_horse_exercise', as: 'unsave_horse_exercise'
  get 'unsave_horse_course/:id', to: 'course_positions#unsave_horse_course', as: 'unsave_horse_course'
  get 'unsave_pony_course/:id', to: 'course_positions#unsave_pony_course', as: 'unsave_pony_course'
  get 'unsave_pony_exercise/:id', to: 'course_positions#unsave_pony_exercise', as: 'unsave_pony_exercise'

  get 'mark_used_horse_exercise/:id', to: 'course_positions#mark_used_horse_exercise', as: 'mark_used_horse_exercise'
  get 'mark_unused_horse_exercise/:id', to: 'course_positions#mark_unused_horse_exercise',
                                        as: 'mark_unused_horse_exercise'

  get 'mark_used_horse_course/:id', to: 'course_positions#mark_used_horse_course', as: 'mark_used_horse_course'
  get 'mark_unused_horse_course/:id', to: 'course_positions#mark_unused_horse_course', as: 'mark_unused_horse_course'

  get 'mark_used_pony_exercise/:id', to: 'course_positions#mark_used_pony_exercise', as: 'mark_used_pony_exercise'
  get 'mark_unused_pony_exercise/:id', to: 'course_positions#mark_unused_pony_exercise', as: 'mark_unused_pony_exercise'

  get 'mark_used_pony_course/:id', to: 'course_positions#mark_used_pony_course', as: 'mark_used_pony_course'
  get 'mark_unused_pony_course/:id', to: 'course_positions#mark_unused_pony_course', as: 'mark_unused_pony_course'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show"
  root 'welcome#index', as: 'welcome_page', via: :all
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/exercises_controller.rb
# frozen_string_literal: true

class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[show edit update destroy]

  def index
    @exercises = current_user.exercises.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show; end

  def new
    @exercise = Exercise.new
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.user_id = current_user.id

    if @exercise.save
      if @exercise.public
        success = create_associated_records(@exercise)
        if !success
          render :new # Re-render the form with errors
        else
          redirect_to exercises_path(selected_exercise_id: @exercise.id),
                      notice: 'Vingrinājums tika veiksmīgi izveidots.'
        end
      else
        redirect_to exercises_path(selected_exercise_id: @exercise.id), notice: 'Vingrinājums tika veiksmīgi izveidots.'
      end
    else
      render :new
    end
  end

  def update
    @exercise = Exercise.find(params[:id])
    old_exercise_type = @exercise.exercise_type
    old_animal_type = @exercise.animal_type
    was_public = @exercise.public?

    if @exercise.update(exercise_params)
      if !@exercise.public?
        remove_associated_records(@exercise)
        redirect_to exercises_path(selected_exercise_id: @exercise.id),
                    notice: 'Vingrinājums tika veiksmīgi atjaunināts'
      else
        if was_public && (old_exercise_type != @exercise.exercise_type || old_animal_type != @exercise.animal_type)
          remove_associated_records(OpenStruct.new(exercise_type: old_exercise_type, animal_type: old_animal_type,
                                                   id: @exercise.id))
        end
        success = create_associated_records(@exercise)
        if !success
          render :edit # Re-render the form with errors
        else
          redirect_to exercises_path(selected_exercise_id: @exercise.id),
                      notice: 'Vingrinājums tika veiksmīgi atjaunināts.'
        end
      end
    else
      render :edit
    end
  end

  def destroy
    remove_associated_records(@exercise)
    if @exercise.destroy
      redirect_to exercises_url, notice: 'Vingrinājums tika veiksmīgi dzēsts.'
    else
      redirect_to exercises_path(selected_exercise_id: @exercise.id), alert: 'Neizdevās izdzēst vingrinājumu.'
      Rails.logger.error "Dzēšana neizdevās ar kļūdām: #{@exercise.errors}"
    end
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:user_id, :exercise_name, :exercise_description, :animal_type, :exercise_type,
                                     :public, :completed, :canvas_data, :canvas_image)
  end

  def remove_associated_records(exercise)
    case exercise.exercise_type
    when 'vingrinajums'
      case exercise.animal_type
      when 'Ponijs'
        # Remove associated records from pony_exercises table
        PonyExercise.where(exercise_id: exercise.id).destroy_all
      when 'Zirgs'
        # Remove associated records from horse_exercises table
        HorseExercise.where(exercise_id: exercise.id).destroy_all
      end
    when 'marsruts'
      case exercise.animal_type
      when 'Ponijs'
        # Remove associated records from pony_courses table
        PonyCourse.where(exercise_id: exercise.id).destroy_all
      when 'Zirgs'
        # Remove associated records from horse_courses table
        HorseCourse.where(exercise_id: exercise.id).destroy_all
      end
    end
  end

  def create_associated_records(exercise)
    # Ja vingrinājums ir publisks un vingrinājuma veids ir 'vingrinajums'
    if exercise.public? && exercise.exercise_type == 'vingrinajums'
      # Ja dzīvnieka tips ir 'Ponijs'
      if exercise.animal_type == 'Ponijs'
        # Meklē esošu PonyExercise ar tādu pašu nosaukumu
        existing_record = PonyExercise.find_by(title: exercise.exercise_name)
        # Ja eksistējošs ieraksts un tas nav saistīts ar pašreizējo vingrinājumu, pievieno kļūdu un atgriež false
        if existing_record && existing_record.exercise_id != exercise.id
          exercise.errors.add(:base, 'Nosaukums jau eksistē, lai padarītu publiski to nomainiet!')
          return false
        end
        # Izveido vai atrod PonyExercise ar attiecīgajām īpašībām
        PonyExercise.create_with(description: exercise.exercise_description, canvas_image: exercise.canvas_image)
                    .find_or_create_by(title: exercise.exercise_name, exercise_id: exercise.id)
      # Ja dzīvnieka tips ir 'Zirgs'
      elsif exercise.animal_type == 'Zirgs'
        # Meklē esošu HorseExercise ar tādu pašu nosaukumu
        existing_record = HorseExercise.find_by(title: exercise.exercise_name)
        # Ja eksistējošs ieraksts un tas nav saistīts ar pašreizējo vingrinājumu, pievieno kļūdu un atgriež false
        if existing_record && existing_record.exercise_id != exercise.id
          exercise.errors.add(:base, 'Nosaukums jau eksistē, lai padarītu publiski to nomainiet!')
          return false
        end
        # Izveido vai atrod HorseExercise ar attiecīgajām īpašībām
        HorseExercise.create_with(description: exercise.exercise_description, canvas_image: exercise.canvas_image)
                     .find_or_create_by(title: exercise.exercise_name, exercise_id: exercise.id)
      end
    # Ja vingrinājums ir publisks un vingrinājuma veids ir 'marsruts'
    elsif exercise.public? && exercise.exercise_type == 'marsruts'
      # Ja dzīvnieka tips ir 'Ponijs'
      if exercise.animal_type == 'Ponijs'
        # Meklē esošu PonyCourse ar tādu pašu nosaukumu
        existing_record = PonyCourse.find_by(title: exercise.exercise_name)
        # Ja eksistējošs ieraksts un tas nav saistīts ar pašreizējo vingrinājumu, pievieno kļūdu un atgriež false
        if existing_record && existing_record.exercise_id != exercise.id
          exercise.errors.add(:base, 'Nosaukums jau eksistē, lai padarītu publiski to nomainiet!')
          return false
        end
        # Izveido vai atrod PonyCourse ar attiecīgajām īpašībām
        PonyCourse.create_with(description: exercise.exercise_description, canvas_image: exercise.canvas_image)
                  .find_or_create_by(title: exercise.exercise_name, exercise_id: exercise.id)
      # Ja dzīvnieka tips ir 'Zirgs'
      elsif exercise.animal_type == 'Zirgs'
        # Meklē esošu HorseCourse ar tādu pašu nosaukumu
        existing_record = HorseCourse.find_by(title: exercise.exercise_name)
        # Ja eksistējošs ieraksts un tas nav saistīts ar pašreizējo vingrinājumu, pievieno kļūdu un atgriež false
        if existing_record && existing_record.exercise_id != exercise.id
          exercise.errors.add(:base, 'Nosaukums jau eksistē, lai padarītu publiski to nomainiet!')
          return false
        end
        # Izveido vai atrod HorseCourse ar attiecīgajām īpašībām
        HorseCourse.create_with(description: exercise.exercise_description, canvas_image: exercise.canvas_image)
                   .find_or_create_by(title: exercise.exercise_name, exercise_id: exercise.id)
      end
    end
    # Ja visi nosacījumi ir izpildīti, atgriež true
    true
  end
end

app/helpers/exercises_helper.rb
# frozen_string_literal: true

module ExercisesHelper
end

app/views/exercises/_form.html.erb
<div id="step-indicators" class="mb-3">
  <span class="step-indicator">1</span>
  <span class="step-indicator">2</span>
</div>
<%= form_with(model: exercise, local: true, html: { id: "exercise_form" }) do |form| %>
  <!-- Step 1: SVG Library and name -->
  <div id="step-1" class="step">
    <% if @exercise.errors.any? %>
      <div class="error flex justify-center">
        <div id="error_explanation" class="bg-red-100 text-center w-1/2 border border-red-400 text-red-700 px-4 mt-5 mb-5 py-3 rounded">
          <ul>
            <% @exercise.errors.each do |error| %>
              <li><%= error.message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <%end%>
    <div class="field">
      <div class="field">
        <%= form.label :exercise_name, "Novietojuma nosaukums", class: "text-black" %> <span class="text-red-500">*</span>
        <%= form.text_field :exercise_name,  class: "border-2 rounded-lg px-3 py-2 focus:outline-none focus:border-orange-700 block mx-auto" %>
      </div>
      <div class="field">
        <%= form.label :exercise_description, "Novietojuma apraksts", class: "text-black" %> <span class="text-red-500">*</span>
        <%= form.text_area :exercise_description, rows: 5, class: "border-2 rounded-lg px-3 py-2 focus:outline-none focus:border-orange-700 block mx-auto" %>
      </div>
      <div id="svg-library" class="flex justify-center draggable-svg">
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/ob-1.svg" alt="ob-1" class="draggable-image w-10 h-10">
          <div class="info-box">Okseris</div>
        </div>
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/ob-2.svg" alt="ob-2" class="draggable-image w-20 h-10">
          <div class="info-box">Text</div>
        </div>
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/ob-3.svg" alt="ob-3" class="draggable-image w-20 h-10">
          <div class="info-box">Text1</div>
        </div>
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/ob-4.svg" alt="ob-4" class="draggable-image w-20 h-10">
          <div class="info-box">Kārtiņa</div>
        </div>
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/ob-5.svg" alt="ob-5" class="draggable-image w-20 h-10">
          <div class="info-box">Text2</div>
        </div>
        <div class="image-container">
          <img src="/assets/exercise_obsctacles/arrow.svg" alt="ob-6" class="draggable-image w-15 h-10">
          <div class="info-box">Jāšanas virzienes norāde</div>
        </div>
      </div>
      <div id="canvas-container" class="flex justify-center">
        <canvas id="canvas" width="900" height="400" class="border-2 rounded-lg" style="border:1px solid #000000;"></canvas>
        <div id="buttons-container" class="flex flex-col">
          <button id="rotateBtnLeft" class="mb-3"><%= image_tag("rotate-left.svg", alt: "Rotate left button", class: "w-6 h-6") %></button>
          <button id="rotateBtnRight" class="mb-3 mr-3"><%= image_tag("rotate-right.svg", alt: "Rotate right button", class: "w-6 h-6") %></button>
          <button id="removeBtn" class="mb-3"><%= image_tag("delete.svg", alt: "Delete button", class: "w-6 h-6") %></button>
          <button id="clearBtn"><%= image_tag("clear.svg", alt: "Clear canvas button", class: "w-6 h-6") %></button>
        </div>
      </div>
    </div>
  </div>
  <%= form.hidden_field :canvas_data, id: "canvasDataField" %>
  <%= form.hidden_field :canvas_image, id: "canvasImageField" %>
  <!-- Step 2: Animal Type and Exercise Type -->
  <div id="step-2" class="step hidden">
    <div class="field">
      <%= form.label :animal_type, "Kam paredzēts novietojums:", class: "text-black" %>
      <%= form.select :animal_type, ['Ponijs', 'Zirgs'], {}, { class: 'border-2 rounded-lg px-4 py-2 block focus:outline-none focus:border-orange-700' } %>
    </div>
    <div class="field">
      <%= form.label :exercise_type, "Novietojuma tips:", class: "text-black" %>
      <%= form.select :exercise_type, [['Maršuts', 'marsruts'], ['Vingrinājums', 'vingrinajums']], {}, { class: 'border-2 rounded-lg px-3 py-2 focus:outline-none block focus:border-orange-700' } %>
    </div>
    <div class="field">
      <%= form.label :public, "Publiskot novietojumu", class: "text-black" %>
      <%= form.check_box :public, class: "text-black" %>
    </div>
    <div class="field">
      <%= form.label :completed, "Izpildīts novietojums", class: "text-black" %>
      <%= form.check_box :completed, class: "text-black" %>
    </div>
  </div>
<% end %>
<!-- Bottom Navigation Buttons -->
<div id="step-indicators">
  <div id="bottom-step-indicators">
    <span class="step-indicator">1</span>
    <span class="step-indicator">2</span>
  </div>
</div>
<div id="button-container">
  <button id="prevBtn" type="button" class="bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white">Atpakaļ</button>
  <button id="nextBtn" type="button" class="bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white">Nākamais</button>
  <button id="submitBtn" type="button" class="font-bold bg-indigo-600 cursor-pointer text-white py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring focus:ring-indigo-200 focus:ring-opacity-50 ml-5 hidden">Saglabāt</button>
  <% if @exercise.persisted? %>
    <%= button_to 'Dzēst', exercise_path(@exercise), method: :delete, id: "delete-exercise", class: "inline-block px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-700 hover:text-white ml-5" %>
  <% end %>
</div>
<%= stylesheet_link_tag "exercise_form" %>
<%= javascript_include_tag 'exercise_build' %>
<%= javascript_include_tag 'page_indicator' %>

app/views/exercises/edit.html.erb
<div class="p-4 flex items-center justify-between">
  <%= link_to exercises_path, class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white" do %>
    <%= image_tag("arrow.svg", alt: "Arrow button", class: "w-6 h-6") %>
  <% end %>
  <div class="text-center">
    <h1 class="text-xl font-bold ">Rediģēt novietojumu "<%= @exercise.exercise_name%>"</h1>
  </div>
  <div></div>
</div>
<%= render 'form', exercise: @exercise %>

app/views/exercises/index.html.erb
<%= javascript_include_tag 'show_exercises' %>
<%= stylesheet_link_tag "show_exercises" %>
<h1 class="text-black text-center text-xl mt-4 font-bold">Jūsu izveidotie novietojumi</h1>
<div class="flex justify-end mr-5">
  <%= link_to 'Izveidot novietojumu', new_exercise_path, class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white" %>
</div>
<div class="flex justify-center mb-2">
  <%= paginate @exercises %>
</div>
<% if @exercises.any? %>
  <% @exercises.each do |exercise| %>
    <div class="border-b border-gray-600 mb-4 pb-4 ml-5 shadow-md" x-data="{ open: false }">
      <h3 class="text-lg font-bold cursor-pointer text-center" @click="open = !open">
        <%= exercise.exercise_name %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-4 h-4 align-middle ml-1">
          <path fill-rule="evenodd" d="M10 12a1 1 0 0 1-.707-.293l-4-4a1 1 0 0 1 1.414-1.414L10 10.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.707.293z" clip-rule="evenodd" />
        </svg>
      </h3>
      <div class="mt-2 ml-auto mr-5" x-show="open" @click.away="open = false" id="exercise_<%= exercise.id %>" style="display: flex; justify-content: center; align-items: center;">
        <div class=" pb-4 mr-5 flex">
          <div class="mb-4 mt-5 w-full description-container" id="description-container-<%= exercise.id %>">
            <div class="flex flex-col items-center rounded-lg bg-gray-100 shadow-md">
              <strong class="text-bold text-xl underline highlight-text" id="exercise_description">Par novietojumu:</strong>
              <div id="exercise_description_content_<%= exercise.id %>" class="description-content">
                <p class="mr-3 ml-3" id="exercise_description_text_<%= exercise.id %>"><%= exercise.exercise_description %></p>
                <% if exercise.exercise_description.length > 50 %>
                  <button class="show-more-btn" onclick="toggleDescription('exercise_description_text_<%= exercise.id %>')">Rādīt vairāk</button>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Canvas Image -->
          <div class="mt-2 w-full" id="canvas_container_<%= exercise.id %>">
            <div class="image-container border border-black rounded-lg overflow-hidden cursor-pointer" onclick="openPopup(this)">
              <div class="image-wrapper items-center justify-center">
                <%= image_tag("mouse-click-icon.svg", alt: "Click button", class: "click w-6 h-6") %>
                <img class="small-image h-40 max-w-full" src="<%= exercise.canvas_image %>" style="filter: blur(5px);" />
              </div>
            </div>
          </div>
          <!-- Info Box -->
          <div class="mt-2 ml-auto mr-5 w-full" id="info-box-container-<%= exercise.id %>">
            <div class="info-box-index info-box-container" onmouseover="showInfoBox(event, '<%= exercise.id %>')" onmouseleave="hideInfoBox('<%= exercise.id %>')">
              <p>
                <strong class="text-white bg-orange-700 highlight-text" id="animal_type">Novietojuma dzīvnieks:</strong>
                <% if exercise.animal_type == "Zirgs" %>
                  <span class="inline-block rounded bg-gray-300 mr-0 text-gray-600 py-1 px-2">Ponijs</span>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Zirgs</span>
                <% else %>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Ponijs</span>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 ml-0 py-1 px-2">Zirgs</span>
                <% end %>
              </p>
              <p>
                <strong class="text-white bg-orange-700 highlight-text" id="exercise_type">Novietojuma tips:</strong>
                <% if exercise.exercise_type == "marsruts" %>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Maršruts</span>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Vingrinājums</span>
                <% else %>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Maršruts</span>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Vingrinājums</span>
                <% end %>
              </p>
              <p>
                <strong class="text-white bg-orange-700 highlight-text" id="public">Publisks novietojums:</strong>
                <% if exercise.public %>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Jā</span>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Nē</span>
                <% else %>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Jā</span>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Nē</span>
                <% end %>
              </p>
              <p>
                <strong class="text-white bg-orange-700 highlight-text" id="completed">Pabeigts novietojums:</strong>
                <% if exercise.completed %>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Jā</span>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Nē</span>
                <% else %>
                  <span class="inline-block rounded bg-gray-300 text-gray-600 py-1 px-2">Jā</span>
                  <span class="inline-block rounded bg-green-500 ml-0 py-1 px-2">Nē</span>
                <% end %>
              </p>
            </div>
            <div class="info-box-content hidden" id="info-box-content-<%= exercise.id %>">
              <!-- Content for the information box -->
              Šim ir tikai informatīva nozīme, lai veiktu izmaiņas nospiežat pogu rediģēt!
            </div>
          </div>
          <div class="popup-container" style="display: none;">
            <div class="popup-content relative" data-exercise-name="<%= exercise.exercise_name %>">
              <button class="close-btn bg-gray-500 hover:bg-gray-700 text-white px-2 py-1 rounded-full absolute top-0 right-0 m-2" onclick="closePopup(this)">
                <%= image_tag("close-x.svg", alt: "Close button", class: "w-6 h-6") %>
              </button>
              <img class="full-image" src="" alt="Full Image">
              <div class="popup-options flex">
                <button class="print-btn bg-gray-500 hover:bg-gray-700 text-white px-3 py-2 rounded mr-2" onclick="printImage(this)">
                  <%= image_tag("print.svg", alt: "Print button", class: "w-6 h-6") %>
                </button>
                <button class="download-btn bg-green-500 hover:bg-green-700 text-white px-3 py-2 rounded" onclick="downloadImage(this)">
                  <%= image_tag("downloads.png", alt: "Rotate left button", class: "w-6 h-6") %>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- Edit Link -->
        <div class="mt-2" style="display: flex; justify-content: center;">
          <%= link_to 'Rediģēt', edit_exercise_path(exercise), class: "bg-gray-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-900 hover:text-white" %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-black text-center">Nav izveidotu novietojumu</p>
<% end %>
<div class="flex justify-center mt-2 mb-2">
  <%= paginate @exercises %>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const selectedExerciseId = <%= params[:selected_exercise_id].to_i %>;
    if (selectedExerciseId) {
      const selectedExercise = document.getElementById(`exercise_${selectedExerciseId}`);
      if (selectedExercise) {
        selectedExercise.querySelector("[x-data]").__x.$data.open = true;
      }
    }
  });
</script>

app/views/exercises/new.html.erb
<div class="p-4 flex items-center justify-between">
  <%= link_to exercises_path, class: "bg-gray-500 text-white font-bold py-2 px-4 rounded inline-block hover:bg-blue-900 hover:text-white" do %>
    <%= image_tag("arrow.svg", alt: "Arrow button", class: "w-6 h-6") %>
  <% end %>
  <div class="text-center">
    <h1 class="text-black text-xl items-center text-center font-bold mt-4 mb-3">Jauns novietojums</h1>
  </div>
  <div></div>
</div>
<%= render 'form', exercise: @exercise %>

app/views/exercises/show.html.erb
<p>
  <strong class="text-black">Novietojuma nosaukums:</strong>
  <%= @exercise.exercise_name %>
</p>
<p>
  <strong class="text-black">Novietojuma apraksts:</strong>
  <%= @exercise.exercise_description %>
</p>
<p>
  <strong class="text-black">Novietojuma dzīvnieks:</strong>
  <%= @exercise.animal_type %>
</p>
<p>
  <strong class="text-black">Novietojuma tips:</strong>
  <%if @exercise.exercise_type == "marsruts"%>
    <a>Maršruts</a>
  <%else%>
    <a>Vingrinājums</a>
  <%end%>
</p>
<p>
  <strong class="text-black">Publisks novietojums:</strong>
  <%= @exercise.public ? 'Jā' : 'Nē' %>
</p>
<p>
  <strong class="text-black">Pabeigts novietojums:</strong>
  <%= @exercise.completed ? 'Jā' : 'Nē' %>
</p>
<%= link_to 'Rediģēt', edit_exercise_path(@exercise), class: "text-orange-500 hover:text-orange-700" %> |